### PR TITLE
feature: added five themes

### PR DESCRIPTION
**Pull request by masabinhok**
**Pull Request Title:** Add New Themes: Hacktoberfest, Sunshine, Retro, Girly, and Ocean #88

**Description:**

This pull request introduces five new themes to the project:

- **Hacktoberfest**: A vibrant theme inspired by the Hacktoberfest event.
- **Sunshine**: A bright and cheerful theme that brings warmth and positivity.
- **Retro**: A nostalgic theme that evokes classic styles and colors.
- **Girly**: A playful and feminine theme with soft and stylish aesthetics.
- **Ocean**: A calming theme reflecting the soothing colors of the sea.

**Details:**

- Each theme has been created with dedication and reflects thoughtful design choices.
- The theme names are chosen creatively to represent their essence.
- This addition enhances the overall user experience by providing more options for personalization.

**Screenshots:**
Screenshot 2024-10-03 012949
Screenshot 2024-10-03 012917
Screenshot 2024-10-03 012851
Screenshot 2024-10-03 012827
Screenshot 2024-10-03 012743

Thank you for considering this addition!

### CODE REVIEW

**Review by JhohannesK — APPROVED** [review]
LGTM.

But there seem to be a little issue, where switching from the newer ones being added to the older which already existed does not happen.
We would pick that up in another issue.

**Review by darkjoka — APPROVED** [review]

**Comment by masabinhok** [comment]
isn't this deploy on commit; i mean even though pr is merged, i can't see the changes on the real website.

**Comment by JhohannesK** [comment]
> isn't this deploy on commit; i mean even though pr is merged, i can't see the changes on the real website. 

The real website is on the main branch. I merge into preview first and if everything is fine, I move it to main.
So don't worry..your commits would go to main.

**Comment by masabinhok** [comment]
oh, good practice.

**Pull request merged**
