### PR TITLE
Fixed ESLint error

### PR DESCRIPTION
**Pull request by slashexx**

### CODE REVIEW

**Comment by JhohannesK** [comment]
You have conflicts on your branch.

**Comment by slashexx** [comment]
My apologies, seems I was in a hurry.

I'll make the changes from scratch.

**Comment by slashexx** [comment]
Uhh what ?

I'm sorry I didn't mean to push any changes, I just discarded my commits and synced my branch...?

**Comment by JhohannesK** [comment]
@slashexx, are you on the discord page?
if not please join with this link,[link]( https://discord.gg/sHkcYRhY)
There's an issue with eslint and discussion is ongoing..need you there.

**Comment by slashexx** [comment]
Sure thing, I'll be there.

**Pull request closed without merging**
