### PR TITLE
Updated the language section in the web app.

### PR DESCRIPTION
**Pull request by Ham12-3**
I noticed this section where there was english in there: 
image

What I noticed what that the english could not be changed into another language like french to type in. What I mean is that this area here, the language will be changed based on what the user wants to type in: 
image

. I made usse of rapid api and here are my env keys:
NEXT_PUBLIC_RAPID_API_KEY='77890f0a6cmsha97e6b7b4ec8e5ap102585jsn0b40582fa919'
NEXT_PUBLIC_RAPID_API_HOST='google-translator9.p.rapidapi.com'

You could also create yours as well. 
the vercel deployment could fail because of the environment variables

### CODE REVIEW

**Comment by JhohannesK** [comment]
I'm sorry, but I don't understand the description very well.

**Comment by Ham12-3** [comment]
What I meant was that the text that is meant to be typed, I made it possible to change the language by clicking on this english button here: 
image

so I could change the language of what I am typing, for instance, I can type in french, or any other form of language.
this part is where the language gets changed: 
image

**Comment by JhohannesK** [comment]
> What I meant was that the text that is meant to be typed, I made it possible to change the language by clicking on this english button here: image
> 
> so I could change the language of what I am typing, for instance, I can type in french, or any other form of language. this part is where the language gets changed: image

any video to showcase this?
vercel failed to build your PR so I can preview it to see what you're talking about.

gone through the code..
so you do a translation of what's showing?

**Comment by Ham12-3** [comment]
Yeah the vercel is not working because I am using rapidapi for the translation ,
here is my api keys: NEXT_PUBLIC_RAPID_API_KEY='77890f0a6cmsha97e6b7b4ec8e5ap102585jsn0b40582fa919'
NEXT_PUBLIC_RAPID_API_HOST='google-translator9.p.rapidapi.com'

you could also get your apikeys  from rapidapi: https://rapidapi.com/googlecloud/api/google-translate1

**Comment by Ham12-3** [comment]
vercel would not work because it will need the apikeys for the translation to work

**Comment by JhohannesK** [comment]
Let's get a video to see how it works..
Because the whole plan is write down our own words.

So let's see how yours also work

**Comment by Ham12-3** [comment]
here is a video where I am changing the language and then it adds new languages to test with: 

https://github.com/user-attachments/assets/33c3d939-3bdd-4963-9c9d-41a8e9beb61e

**Comment by JhohannesK** [comment]
> here is a video where I am changing the language and then it adds new languages to test with:
> 
>  bandicam.2024-10-03.21-11-13-342.mp4

oh no... this is different from what we wanted.
so same way load english words from a file and display them, we want same for other languages too.. so if the user changes the language from say english to french, we load french words for the user. every word becomes french.
Hope I'm clear with this?
lemme know if it isn't

**Comment by Ham12-3** [comment]
yes that is it exactly

**Comment by JhohannesK** [comment]
@Ham12-3 Are we on the same page here?

**Comment by Ham12-3** [comment]
Yes we are

**Comment by Ham12-3** [comment]
please close the PR, I haven't found solution yet

**Pull request closed without merging**
