### PR TITLE
Improve ResultsPage UI with Enhanced Statistics Display and Flex Layout

### PR DESCRIPTION
**Pull request by Mefisto04**
### Pull Request Description:

This pull request enhances the UI of the `ResultsPage` by adding more detailed statistics and improving the layout for better user experience.

#### Changes Made:
1. **Added Current Standing Section:**
   - Included a new `p` tag displaying the user’s "Current Standing" for better visual feedback.
   - Added another `p` tag to show "Show for statistics: English," which can dynamically reflect the statistics category.

2. **Added Flex Containers for Statistics:**
   - Three rounded boxes now display **Time**, **Average Speed (WPM)**, and **Accuracy**, styled with Tailwind CSS.
   - These statistics are calculated using data from the store (`typedEntries`, `time`) and displayed in a responsive flex layout.

3. **Repositioned the Retake Button:**
   - The **Retake** button has been moved to the bottom of the page, after the statistics, for better flow and user interaction.

4. **Styling Enhancements:**
   - Used Tailwind CSS to create a modern look with flex layouts, rounded corners, and hover effects.
   - Applied text styling and padding for better readability and overall UI clarity.

#### Screenshots (if applicable):
image

Let me know if you need further refinements or adjustments to the logic or UI!

### CODE REVIEW

**Review by JhohannesK — CHANGES_REQUESTED** [review]
image
I changed the theme and this is what I get. the cards has no border.

* it's also quite different from the image I attached to the issue. A lot of details were missing
* The language aspect is supposed to be a dropdown, which we would popluate with the languages available in the application.
* You forgot to include the all-time statistics sections also. You can hold on onto that for now. We would add after account creation has been activated.
* Your button also looks different from what was in the image

### What I think you can do also.
Create a reusable component for the cards which would inputs such has label/title and value.

**Comment by JhohannesK** [comment]
Is this still in progress?

**Comment by d-a-ve** [comment]
Hey @Mefisto04, whats up with this PR? Is it still being worked on?

**Comment by Mefisto04** [comment]
no, it causes some conflicts, if you want to contribute in this you can.

**Comment by JhohannesK** [comment]
@d-a-ve , are you taking this?

**Comment by d-a-ve** [comment]
I have seen the design. Yeah, I can do it.

If it's assigned to me, I know that @Mefisto04 is fine with me working on it

**Pull request closed without merging**
