### PR TITLE
Update Contributors list in README and fix typo

### PR DESCRIPTION
**Pull request by iampearlep**

### CODE REVIEW

**Comment by JhohannesK** [comment]
Are you done?

**Comment by iampearlep** [comment]
> Are you done?

Yes, I'm done.

**Comment by JhohannesK** [comment]
Tell how and when it works please?
a lil bit of description of what this PR does.

**Comment by iampearlep** [comment]
> Tell how and when it works please? a lil bit of description of what this PR does.

It updates the Contributors section in the README file to reflect the latest contributors to the project. It uses a GitHub Action to automate updating the contributors list. The action runs on every push to the preview branch and updates the README file accordingly. The changes should be visible in the README file after the action is completed successfully.

**Pull request merged**
