### PR TITLE
Deleted old lint config

### PR DESCRIPTION
**Pull request by slashexx**
Pull Request Template
⚠️ This helps you complete a pull request. Please follow the instructions below. Reminder that you are bound to abide by the [Code of Conduct](https://github.com/CODE_OF_CONDUCT.md) ⚠️

Submission Checklist
Please complete the below checklist. Failure to follow these instructions may result in your pull request being closed without review.

What issue does this PR close?

closes # (issue number)

Description of file changes
- Updated the ESLint configuration to detect the React version, addressing the warning about the version not being specified. 
- Note that further work will be needed to resolve this issue completely.
- Deleted the old .eslintrc.json file to prevent conflicts with the new configuration.
- Commented out a deprecated line in the Husky configuration, which will be removed in version 10.0.0 as indicated by the command-line message upon committing.
- Added a ^ before the React version in package.json to allow for minor version updates.

### Is this PR still in progress or completed?
- [ ] This PR is still a work in progress (WIP)
- [x] This PR is completed and ready for review
- [x] Did you edit the package.json or pnpm.yaml? If yes, explain reason for modification and add the `dependencies` label to this PR. <br>
Added a ^ before the React version in package.json to allow for minor version updates.

### CODE REVIEW

**Comment by JhohannesK** [comment]
image

**Comment by slashexx** [comment]
Forgot to update lock file, my bad :(

Question : Should I now update lock file or reset the package.json for the fixed react version (removing ^)

**Comment by JhohannesK** [comment]
> Forgot to update lock file, my bad :(
> 
> Question : Should I now update lock file or reset the package.json for the fixed react version (removing ^)

reset it if that's going to be an issue..I'll take care of that

**Comment by slashexx** [comment]
I've reset the package.json for now, hopefully there's no error in CI now.

**Comment by slashexx** [comment]
@JhohannesK can you please review?

**Pull request merged**
