### PR TITLE
Revert "(Fixes: #155) Update ESLint configuration to use flat config format"

### PR DESCRIPTION
**Pull request by JhohannesK**
Reverts JhohannesK/TipoHiZ#161

image
There is an when trying to run linting command.

### CODE REVIEW

**Comment by slashexx** [comment]
Sure thing, I'll work on this.

**Comment by slashexx** [comment]
I did some stuff and maybe the globals dependency wasn't added to devDeps

Anyways, I ran the lint command again after making some changes but now I can't seem to get over this error, should I ask it in the discussions tab ?

**Comment by slashexx** [comment]
I did some changes and maybe the globals dependency wasn't added in the devDeps.

Also, I ran the lint command after making the changes and got this error I can't get over. Should I ask this in the discussions tab ?

Screenshot From 2024-10-08 18-44-50

**Comment by JhohannesK** [comment]
> I did some changes and maybe the globals dependency wasn't added in the devDeps.
> 
> Also, I ran the lint command after making the changes and got this error I can't get over. Should I ask this in the discussions tab ?
> 
> Screenshot From 2024-10-08 18-44-50

Delete that file..We are using the tsx version of that file..I thought it had already been deleted.

**Pull request merged**
