### PR TITLE
fixes navbar issues #143

### LINKED ISSUE #143: [FEATURE] Navbar responsive  adjustments
### Is this a unique feature?

- [X] I have checked "open" AND "closed" issues and this is not a duplicate

### Is your feature request related to a problem/unavailable functionality? Please describe.

i have created a hamburger menu for responsive navbar that matches with theme color
image
image
image

### Proposed Solution

i have seen this overflowing issues with the navbar 
image
 
i picked this issues and fixed it by adding hamburger menu 

### Screenshots

_No response_

### Do you want to work on this issue?

Yes

### If "yes" to above, please explain how you would technically implement this (issue will not be assigned if this is skipped)

I would like to add a hamburger menu that matches with theme colors which look better on screen by avoiding overflow of content in navbar

### PR DESCRIPTION
**Pull request by mokshanirugutti**
fixes  #143 
made nav bar more responsive

### CODE REVIEW

**Comment by mokshanirugutti** [comment]
image

fixed  issue: Text fails to display in some themes

**Review by JhohannesK — COMMENTED** [review]
Can you resolve the conflict on your branch please

**Comment by JhohannesK** [comment]
> Can you resolve the conflict on your branch please

Request for review when this is done.

**Review by JhohannesK — APPROVED** [review]

**Review by JhohannesK — APPROVED** [review]
LGTM

**Pull request merged**
