### PR TITLE
feature/theme-selection-preview

### LINKED ISSUE #183: [FEATURE] Theme color preview on selection
### Is this a unique feature?

- [X] I have checked "open" AND "closed" issues and this is not a duplicate

### Is your feature request related to a problem/unavailable functionality? Please describe.

This is addon to theme selection. This update enable color preview before selecting the theme
image

### Proposed Solution

This feature will add main color codes as preview while selecting the theme 
the end result will look something like this 
image

### Screenshots

_No response_

### Do you want to work on this issue?

Yes

### If "yes" to above, please explain how you would technically implement this (issue will not be assigned if this is skipped)

i will make map main colors codes that highlight the theme and display them on  theme selection menu

### PR DESCRIPTION
**Pull request by mokshanirugutti**
### What issue does this PR closes?
close #183 
This PR adds new feature 
- with this feature user can preview the color code of theme before selection

previously the selection area looks like this 
image

- with   new feature it looks like this 
image

### Description of file changes
- theme-choose.tsx - added code to display color code
- theme.constant.ts - updated color codes

### Is this PR still in progress or completed?
- [x] This PR is still a work in progress (WIP) - `completed`
- [x] This PR is completed and ready for review - `yes`
- [x] Did you edit the package.json or pnpm.yaml? If yes, explain reason for modification and add the `dependencies` label to this PR. <br>  - `no`

### CODE REVIEW

**Comment by JhohannesK** [comment]
Doesn't work properly, 
some themes don't change when you click on them
image
you can see I tried moving back to `dark` but I'm still on `girly`

**Comment by mokshanirugutti** [comment]
??

https://github.com/user-attachments/assets/99ee99f6-494c-4d61-9331-5e3bac358f80

i even tried restarting local server for a second check

**Comment by mokshanirugutti** [comment]
i have made some additional changes in the code,
let me know if the issue is persistent

**Comment by JhohannesK** [comment]
You deleted eslint on your end?
image

**Pull request merged**
