### PR TITLE
social links added

### PR DESCRIPTION
**Pull request by sunny7899**

### CODE REVIEW

**Comment by JhohannesK** [comment]
image

would be nice using icons.
gimme some time.... I'd pull you a design to use

You should always link the issue your PR seems to resolve in your PRs.

**Comment by sunny7899** [comment]
Ok sure @JhohannesK

**Comment by JhohannesK** [comment]
image

let's have it done like this

**Comment by sunny7899** [comment]
Sure

**Comment by JhohannesK** [comment]
@sunny7899 vercel deployment check has failed.

**Comment by JhohannesK** [comment]
image

**Comment by sunny7899** [comment]
Hii @JhohannesK I AM using 1 package to add social media links. is it ok?

**Comment by JhohannesK** [comment]
> Hii @JhohannesK I AM using 1 package to add social media links. is it ok? I think all checks are passing

Please find svgs for the icons and use that instead.
We want it matching wih the theme.

**Comment by sunny7899** [comment]
@JhohannesK PR updated pls tag hacktoberfest

**Comment by JhohannesK** [comment]
What you did is different from the image I sent you

You images are also big. use X logo and not twitter logo.

**Comment by sunny7899** [comment]
@JhohannesK  pls check code is updated. pls merge with hacktoberfest-accepted tag

**Review by JhohannesK — APPROVED** [review]
LGTM, 

you forgot the circle around them though 😂😂

**Pull request merged**
